'use strict';

(() => {
  const featureCatalog = Object.freeze({
    chat: {
      id: 'chat',
      featureType: 'iaChat',
      variantOf: null,
      variantKind: 'core',
      kind: 'panel',
      kicker: '◈ IA CHAT',
      title: 'Conversation cockpit',
      description: 'Dialogue avec NEXUS, prompts rapides et commandes IA.',
      preview: 'ai',
      action: { type: 'panel', target: 'chat' },
    },
    projectsDashboard: {
      id: 'projectsDashboard',
      featureType: 'workflow',
      kind: 'panel',
      kicker: '◉ DASHBOARD',
      title: 'Pilotage quotidien',
      description: 'Projets actifs, taches en cours et vision de progression.',
      preview: 'projects',
      action: { type: 'panel', target: 'dashboard' },
    },
    personalityProfile: {
      id: 'personalityProfile',
      featureType: 'systemProfile',
      kind: 'panel',
      kicker: '◎ PERSONNALITE',
      title: 'Profil NEXUS',
      description: 'Ton, style, proactivite et regles de comportement visibles.',
      preview: 'personality',
      action: { type: 'panel', target: 'personality' },
    },
    actionsLog: {
      id: 'actionsLog',
      featureType: 'activityLog',
      kind: 'panel',
      kicker: '◆ JOURNAL IA',
      title: 'Trace operationnelle',
      description: 'Alertes, actions declenchees et derniere activite cockpit.',
      preview: 'actions',
      action: { type: 'panel', target: 'actions' },
    },
    marketBrief: {
      id: 'marketBrief',
      featureType: 'iaChat',
      variantOf: 'chat',
      variantKind: 'prompt-brief',
      kind: 'prompt',
      kicker: '◈ MARCHES',
      title: 'Briefing marche',
      description: 'Ouvre le chat avec un prompt de veille crypto et bourse.',
      preview: 'market',
      action: { type: 'quickPrompt', promptType: 'market' },
    },
    projectReview: {
      id: 'projectReview',
      featureType: 'iaChat',
      variantOf: 'chat',
      variantKind: 'prompt-project-review',
      kind: 'prompt',
      kicker: '◉ PROJETS',
      title: 'Revue projets',
      description: 'Synthese rapide des priorites et de l organisation actuelle.',
      preview: 'projects',
      action: { type: 'quickPrompt', promptType: 'projects' },
    },
    dailyPlan: {
      id: 'dailyPlan',
      featureType: 'iaChat',
      variantOf: 'chat',
      variantKind: 'prompt-plan',
      kind: 'prompt',
      kicker: '◎ PLAN DU JOUR',
      title: 'Briefing quotidien',
      description: 'Construit un plan de jour a partir des taches et projets actifs.',
      preview: 'plan',
      action: { type: 'quickPrompt', promptType: 'plan' },
    },
    planningCalendar: {
      id: 'planningCalendar',
      featureType: 'planning',
      variantOf: null,
      variantKind: 'core',
      kind: 'panel',
      kicker: '◎ PLANNING',
      title: 'Calendrier cockpit',
      description: 'Affiche un calendrier mensuel complet avec zoom sur chaque jour.',
      preview: 'planning',
      action: { type: 'panel', target: 'planning' },
    },
    documentNotebook: {
      id: 'documentNotebook',
      featureType: 'document',
      variantOf: null,
      variantKind: 'core',
      kind: 'panel',
      kicker: '◆ DOCUMENTS',
      title: 'Carnet de notes',
      description: 'Affiche des notes en cartes et ouvre chaque document en grand pour l editer.',
      preview: 'document',
      action: { type: 'panel', target: 'document' },
    },
    systemSettings: {
      id: 'systemSettings',
      featureType: 'settings',
      kind: 'settings',
      kicker: '◈ SYSTEME',
      title: 'Configuration IA',
      description: 'Ouvre le modal de configuration pour choisir provider, modele et nom du pilote.',
      preview: 'config',
      action: { type: 'settings' },
    },
    dashboardControl: {
      id: 'dashboardControl',
      featureType: 'workflow',
      kind: 'panel',
      kicker: '◎ CONTROLE',
      title: 'Etat du cockpit',
      description: 'Revient au dashboard pour controler projets, taches et progression.',
      preview: 'status',
      action: { type: 'panel', target: 'dashboard' },
    },
    chatConsole: {
      id: 'chatConsole',
      featureType: 'iaChat',
      variantOf: 'chat',
      variantKind: 'panel-console',
      kind: 'panel',
      kicker: '◆ INTERFACE',
      title: 'Console IA',
      description: 'Reprend la main sur le chat pour reconfigurer le systeme par commandes naturelles.',
      preview: 'voice',
      action: { type: 'panel', target: 'chat' },
    },
  });

  globalThis.NEXUS_FEATURE_CATALOG = featureCatalog;
})();